#ifndef DATAANALYSISGLOBAL_H
#define DATAANALYSISGLOBAL_H
#include <QtCore/QtGlobal>

#if defined(DATAANALYSIS_PLUGIN_BUILD)
#define DATAANALYSIS_API Q_DECL_EXPORT
#else
#define DATAANALYSIS_API Q_DECL_IMPORT
#endif

// Q_DECL_IMPORT.
#endif  // DATAANALYSISGLOBAL_H
