#ifndef DASYSTEMNODESGLOBAL_H
#define DASYSTEMNODESGLOBAL_H
#include <QtCore/QtGlobal>

#if defined(DASYSTEMNODES_PLUGIN_BUILD)
#define DASYSTEMNODES_API Q_DECL_EXPORT
#else
#define DASYSTEMNODES_API Q_DECL_IMPORT
#endif

// Q_DECL_IMPORT.
#endif  // DASYSTEMNODESGLOBAL_H
