#ifndef DAPYCOMMONWIDGETSAPI_H
#define DAPYCOMMONWIDGETSAPI_H
#include <QtCore/QtGlobal>

#if defined(DAPYCOMMONWIDGETS_BUILD)
#define DAPYCOMMONWIDGETS_API Q_DECL_EXPORT
#else
#define DAPYCOMMONWIDGETS_API Q_DECL_IMPORT
#endif

// Q_DECL_IMPORT.
#endif  // DAPYCOMMONWIDGETSAPI_H
