#ifndef DAAXOFFICEWRAPPERGLOBAL_H
#define DAAXOFFICEWRAPPERGLOBAL_H
#include <QtCore/QtGlobal>
#include "DAGlobals.h"

#if defined(DAAXOFFICEWRAPPER_BUILDLIB)
#define DAAXOFFICEWRAPPER_API Q_DECL_EXPORT
#else
#ifdef Q_CC_MSVC
#define DAAXOFFICEWRAPPER_API Q_DECL_IMPORT
#else
#define DAAXOFFICEWRAPPER_API Q_DECL_IMPORT
#endif
#endif


#endif  // DAAXOFFICEWRAPPERGLOBAL_H
