#ifndef DAMESSAGEHANDLERGLOBAL_H
#define DAMESSAGEHANDLERGLOBAL_H
#include <QtCore/QtGlobal>
#include "DAGlobals.h"

#if defined(DAMESSAGEHANDLER_BUILDLIB)
#define DAMESSAGEHANDLER_API	Q_DECL_EXPORT
#else
#define DAMESSAGEHANDLER_API	Q_DECL_IMPORT
#endif

#endif // DAINTERFACEGLOBAL_H
