#ifndef DAUTILITYNODEPLUGINAPI_H
#define DAUTILITYNODEPLUGINAPI_H
#include <QtCore/QtGlobal>
#include "DAGlobals.h"

#if defined(DAUTILITYNODEPLUGIN_BUILDLIB)
#define DAUTILITYNODEPLUGIN_API Q_DECL_EXPORT
#else
#define DAUTILITYNODEPLUGIN_API Q_DECL_IMPORT
#endif
#ifndef IID_DAUTILITYNODEPLUGIN
#define IID_DAUTILITYNODEPLUGIN "DA.Node.Utility"
#endif
#ifndef DAUTILITYNODEPLUGIN_NODEPROTOTYPE
#define DAUTILITYNODEPLUGIN_NODEPROTOTYPE(name) IID_DAUTILITYNODEPLUGIN "." #name
#endif
#endif  // DAUTILITYNODEPLUGINAPI_H
