name: CMake-build

on:
  push:
    branches:
      - master
      - dev

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest  # 最新版 Windows
    strategy:
      matrix:
        qt_version: [5.15.2]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache Python
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\Programs\Python
        key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt') }}

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'  # 至少 Python 3.7

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat

    - name: Install zlib via vcpkg
      run: |
        cd vcpkg
        .\vcpkg install zlib:x64-windows

    - name: Cache Qt
      uses: actions/cache@v3
      with:
        path: C:\Qt
        key: ${{ runner.os }}-qt-${{ hashFiles('.github/workflow-cache-version-file.txt') }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
          version: ${{ matrix.qt_version }}
          dir: C:\Qt

    - name: build 3rdparty
      working-directory: src/3rdparty
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cmake --install .

    - name: build the project
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release